//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioDetail
    {
        public int Id { get; set; }
        public string Coin { get; set; }
        public double Quantity { get; set; }
        public double BuyPrice { get; set; }
        public double TotalInvested { get; set; }
        public int UesrId { get; set; }
    }
}
